### ISSUE TITLE
Host/Port is required when selecting a local endpoint

### ISSUE THREAD

**Issue by kberkos-public** [IBM/operator-collection-sdk-vscode-extension#117]
#### What did you do?
I attempted to create an operator using the VSCode extension. When prompted what type of endpoint I wanted to create, I selected local. I was then prompted for a host, and when hitting "Enter" to skip I received the error message "ZosEndpoint host is required".

#### What did you expect to see?

I expected the extension to let me create a local endpoint.

#### What did you see instead? Under which circumstances?

![image](https://github.com/IBM/operator-collection-sdk-vscode-extension/assets/35109788/990ac52f-22ce-4853-894e-7918ca810060)

#### Possible Solution
Allow users to skip host/port when the endpoint type is local.

**Comment by yemi-kelani** [comment]
#126
