### ISSUE TITLE
signature secrets missing after using VS code extension to upgrade an operator

### ISSUE THREAD

**Issue by adn1107** [IBM/operator-collection-sdk-vscode-extension#120]
![image](https://github.com/IBM/operator-collection-sdk-vscode-extension/assets/1631330/9391fd91-f66d-408c-8cf3-f67b39ccbde2)
![image](https://github.com/IBM/operator-collection-sdk-vscode-extension/assets/1631330/f46ba5de-d10a-4fc9-a279-43bdcb564de6)

**Comment by freemanlatrell** [comment]
Resolved in PR #129
