### ISSUE TITLE
OC login field validation doesn't accept underscores

### ISSUE THREAD

**Issue by freemanlatrell** [IBM/operator-collection-sdk-vscode-extension#122]
## Bug Report

There seems to be an issue in with the `oc login` field validation, as it's currently flagging the following auto-generated token containing an underscore 

![image](https://github.com/IBM/operator-collection-sdk-vscode-extension/assets/24191850/9fe159cf-f81d-4031-83e6-034420814e96)

**Comment by freemanlatrell** [comment]
Correct....this issue only occurs when the underscore follows `sha256~`

**Comment by yemi-kelani** [comment]
#125
