### ISSUE TITLE
Truncate the name of branch before we use it for Openshift resource names

### ISSUE THREAD

**Issue by yemi-kelani** [IBM/operator-collection-sdk-vscode-extension#137]
#### What did you do?

Created a pull request for a branch with a long name (`file-scaffolding-tests`).

#### What did you expect to see?

Test cases passing

#### What did you see instead? Under which circumstances?

Test cases fail because ZosCloudBroker was undefined. It was not created because this issue excessively long branch names cause failures when used in testing pipeline.

**Comment by MariandreaMV** [comment]
I have successfully reproduced the error. It is related to the service name length in the cloud broker registry. The issue stems from the concatenation method employed by the broker, resulting in a service name **exceeding** the permissible 63 characters. This violates the DNS label standard outlined in [RFC 1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names), which mandates:

A maximum of 63 characters
Exclusively lowercase alphanumeric characters or '-'
Commencing and concluding with an alphanumeric character
Enclosed with this message is a screenshot illustrating the error and the 63-character validation rule.

Given the nature of this problem, I have decided to close the current issue. However, recognizing the importance of addressing this matter, I intend to open a new one specifically dedicated to the z/OS cloudbroker.

Attaching the error here 

![Screenshot 2024-01-11 at 4 22 35 PM](https://github.com/IBM/operator-collection-sdk-vscode-extension/assets/23127680/3e9f2c44-c37e-4ec1-a566-3e4273bf4fc7)
