### ISSUE TITLE
Purpose of cog wheel on an error message is unclear

### ISSUE THREAD

**Issue by mayur-raja** [IBM/operator-collection-sdk-vscode-extension#15]
Purpose of cog wheel on an error message is unclear. The hover help states 'Configure Notification'. Clicking on it states 'Manage Extension'. But one cannot actually perform any function.

#### What did you do?

I just tried to login in to an empty server to cause an error message to pop up. But this seems to be true for all error messages.

#### What did you expect to see?

Some action to occur when the cog wheel symbol on a message was selected.

#### What did you see instead? Under which circumstances?

Nothing. 

#### Possible Solution

Either add a valid action or remove the cog wheel symbol from all messages.

**Comment by yemi-kelani** [comment]
It doesn't seem like there is a straightforward way to resolve this with the current `vscode` api.
