### ISSUE TITLE
There should be a way to say don't show the 'Do you want to open an external website ?' message 

### ISSUE THREAD

**Issue by mayur-raja** [IBM/operator-collection-sdk-vscode-extension#17]
#### Describe the problem you need a feature to resolve.

To keep popping up the 'Do you want to open an external website ?' message soon becomes mundane. Also, the message states open, but actually allows two other functions or Cancel to be performed too. And selecting Cancel incorrectly shows error message 'Failure opening external link'. This error message should not be issued.

#### Describe the solution you'd like.

There needs to be a way to select a default action and to say 'don't show this message again'.

Also, the documentation needs to explain the purpose of each action. What does each action actually achieve for a user ?

**Comment by yemi-kelani** [comment]
It seems like this is a VSCode security feature that appears when opening external links. There may not be a way to circumvent the message on the extension side. That being said, users do have the option to configure their `trusted domains` to bypass it:

<img width="823" alt="configureTrustedDomains_1" src="https://github.com/IBM/operator-collection-sdk-vscode-extension/assets/91276489/177dbbe0-b967-461f-ad0c-d7ec3cbf1d7a">configureTrustedDomains_1.png

<img width="257" alt="configureTrustedDomains_2" src="https://github.com/IBM/operator-collection-sdk-vscode-extension/assets/91276489/3ab730c9-96d4-45c4-8332-ea3a7da9732d">

<img width="379" alt="configureTrustedDomains_3" src="https://github.com/IBM/operator-collection-sdk-vscode-extension/assets/91276489/706f8f7a-1b39-47bf-bb02-021bc4e9575b">
