### ISSUE TITLE
Be able to access the log for resources that failed to be defined

### ISSUE THREAD

**Issue by mayur-raja** [IBM/operator-collection-sdk-vscode-extension#18]
#### Describe the problem you need a feature to resolve.

Some time ago, I had defined an MQ local queue called q1 which had failed to be defined for some reason and hence had a red X in a circle next to it. I select it and attempted to Preview/edit it. Opening the subsequent URL took me to the OpenShift console where I was able to see details about the queue. The Conditions list does indeed show that the queue failed to be defined but, the error log may show precisely why the queue failed to be defined. 

#### Describe the solution you'd like.

It would be nice if there was a way to access the error log.

**Comment by yemi-kelani** [comment]
#89
