### ISSUE TITLE
Move "view verbose logs" button to the custom resource bars

### ISSUE THREAD

**Issue by yemi-kelani** [IBM/operator-collection-sdk-vscode-extension#38]
#### Describe the problem you need a feature to resolve.

In order to view a verbose log, an instance of a custom resource is necessary. It may be a good idea to only allow the option to view those logs be enable when specific instances already exist.

#### Describe the solution you'd like.

 Move the view verbose logs button to the Custom resource bars

**Comment by freemanlatrell** [comment]
@yemi-kelani Let's hold off on this one until further discussion.
