### ISSUE TITLE
If project is updated during an operator's creation, it fails to create the operator and renders create and delete buttons useless

### ISSUE THREAD

**Issue by yemi-kelani** [IBM/operator-collection-sdk-vscode-extension#43]
#### What did you do?

Steps to reproduce:
- Click create operator button, before it finishes update project 
- Wait til command concludes
- Navigate back to original project

#### What did you expect to see?

An operator created in that namespace, whether it succeeded or failed.

#### What did you see instead? Under which circumstances?

- It creates the operator collection but fails to create the operator in original namespace.
- If you navigate back to the original namespace and click the create operator button you'll see a message saying it was created successfully however it does not create it.
- If you click delete operator, you'll see a deleted successfully message however the operator collection will not be deleted. The redeploy collection and redeploy operator commands both fails.
- A Failed sub-operator config lives in OpenShift but is not shown in extension even after refreshing the resources panel
- Clicking view/edit resource button on the operator fails as well: 
```
Error running command operator-collection-sdk.openEditLink: Cannot read properties of undefined (reading 'link'). This is likely caused by the extension that contributes operator-collection-sdk.openEditLink.
```

In order to fix this broken state, you have to delete the sub-operator config manually in OpenShift.

**Comment by freemanlatrell** [comment]
Fixed. Closing
