### ISSUE TITLE
Double clicking on any of the items in 'Help and Additional Resources' should just open the external link

### ISSUE THREAD

**Issue by mayur-raja** [IBM/operator-collection-sdk-vscode-extension#5]
## Feature Request

Double clicking on any of the items in 'Help and Additional Resources' should just open the external link. Currently, the Open External link sphere symbol is displayed and it is not obvious that this symbol needs to be clicked on. Though, clicking on it does indeed open the external link. 

#### Describe the solution you'd like.

Double clicking on any of the items in 'Help and Additional Resources' should just open the external link. Users would normally expect to be able to double click on an item. 

Actually, this applies to items under all categories.

**Comment by freemanlatrell** [comment]
Complete. Closing
