### ISSUE TITLE
Auto generate missing resources.

### ISSUE THREAD

**Issue by mayur-raja** [IBM/operator-collection-sdk-vscode-extension#66]
#### Describe the problem you need a feature to resolve.

The recent schema validation highlights missing resources e.g. galaxy.yml file is missing in the problems list.
A option(s) could be added to allow users to auto generate missing resources.

#### Describe the solution you'd like.

Skeleton files could be created for missing resources with best guess values which users could manually change or complete.

**Comment by yemi-kelani** [comment]
closed with #128
