### ISSUE TITLE
The documentation should explain precisely how to 'Log in to OpenShift'

### ISSUE THREAD

**Issue by mayur-raja** [IBM/operator-collection-sdk-vscode-extension#7]
The README.md for the VS Code extension. 

### Which section(s) is the issue in?

The section is missing. 

### What needs fixing?

Explain precisely how a user obtains the server URL and token required to 'Log in to OpenShift'.

**Comment by yemi-kelani** [comment]
Directs can be found in [readme.md](https://github.com/IBM/operator-collection-sdk-vscode-extension#manage-your-openshift-cluster-connection-and-project) under the "Manage Your Openshift Cluster Connection and Project Section" in the form of a .gif file.
