### ISSUE TITLE
Update source in linter messages to point to the OC spec

### ISSUE THREAD

**Issue by freemanlatrell** [IBM/operator-collection-sdk-vscode-extension#74]
## Bug Report
We should update the source in the messages below to point to the Operator Collection Spec hosted on Github. 

![image](https://github.com/IBM/operator-collection-sdk-vscode-extension/assets/24191850/dbbfe4d3-ed6a-499c-987d-edcda841f2d6)

**Comment by eduardo-at** [comment]
Theres 2 types of diagnostics, one comes from the redhat yaml extension processing the json-schema which shows as the screenshot above, and the other is the ones we create via the linter we wrote, the ones from the linter we wrote we can add source but for the diagnostics coming from the redhat yaml extension like the one in the screenshot we cannot change the source it links to.

**Comment by freemanlatrell** [comment]
Closing
