### ISSUE TITLE
Display the version of the IBM Operator Collection SDK that is installed

### ISSUE THREAD

**Issue by mayur-raja** [IBM/operator-collection-sdk-vscode-extension#8]
#### Describe the problem you need a feature to resolve.

Display the version of the IBM Operator Collection SDK that is installed

#### Describe the solution you'd like.

Display the version somewhere in the IBM OPERATOR COLLECTION SDK box at the top left of the screen, and/or on the hover help for the operator collection SDK symbol on the left.

**Comment by freemanlatrell** [comment]
Fixed in PR https://github.com/IBM/operator-collection-sdk-vscode-extension/pull/68
