### ISSUE TITLE
View resource occasionally errors

### ISSUE THREAD

**Issue by yemi-kelani** [IBM/operator-collection-sdk-vscode-extension#83]
#### What did you do?

click view resources when during an operation, or even after it has finished.

#### What did you expect to see?

should work or fail gracefully.

#### What did you see instead? Under which circumstances?

<img width="1728" alt="f6" src="https://github.com/IBM/operator-collection-sdk-vscode-extension/assets/91276489/4576efa1-c320-4203-8f83-c818e9996142">

The argument most likely comes in as undefined and the switch case thinks its an invalid resource type.

**Comment by freemanlatrell** [comment]
Resolved. Closing
