### ISSUE TITLE
Attempt to download logs for Container: init fails

### ISSUE THREAD

**Issue by mayur-raja** [IBM/operator-collection-sdk-vscode-extension#9]
## Bug Report

I clicked on the 'Download Logs' symbol to the right of 'IBM OPERATOR COLLECTION SDK -> Container: init' and it failed with: 

Unable to download log
Failure retrieving Pod logs. Forbidden.

There was no other indication of what went wrong, where one could look for further info, and how one could resolve the situation. 

#### What did you do?

I clicked on the 'Download Logs' symbol to the right of 'IBM OPERATOR COLLECTION SDK -> Container: init' .

#### What did you expect to see?

The log or logs to be downloaded. 

#### What did you see instead? Under which circumstances?

Errors: 

Unable to download log
Failure retrieving Pod logs. Forbidden.

#### Possible Solution

The logs should be downloaded and in the event that they cannot be downloaded, there needs to be a clear indication of why not and where one could look to resolve the situation. 

#### Additional context

An attempt to load the logs for 'Container: mayur-test-mq-resources-operator' also failed with the same error messages.

Also, an attempt to load the verbose logs failed with 'Failure retrieving Custom Resource instance names. Forbidden'.

**Comment by freemanlatrell** [comment]
Fixed. Closing
